### PR TITLE
review GitHub workflow

### PR DESCRIPTION
**Pull request by darowsluk**
- [x] Merging creates a pull request
- [x] Merges to dev by default
- [x] Requires approving review
- [x] Includes administrators

### CODE REVIEW

**Comment by darowsluk** [comment]
Suggestions TODO (if possible):

1. Automatically add to new Pull Request:
- owner
- reviewer (team: "developers") - will it work?
- force label (bug, feature, etc.)

**Comment by darowsluk** [comment]
@knutm92 Approve this review to enable me to merge. This will finalize the test as passing.

**Review by knutm92 — APPROVED** [review]
@darowsluk 
These are some good suggestions in the above TODO to automate the workflow. GitHub does not seem to allow for such auto-fills in settings. There are apps/actions that should automate some fields:
https://probot.github.io/apps/auto-assign/
https://github.com/marketplace/actions/auto-author-assign
however, auto-assign doesn't do what it intends when tested. I would not investigate further and keep it as is with a suggestion that we remember to add a label to each PR as a best practice.

**Comment by darowsluk** [comment]
Sounds good. In that case the task can be closed. 👍

**Pull request merged**
